# Copyright (c) 2013 The SAYCBridge Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

application: saycbot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.png)
  static_files: \1
  upload: (.*\.png)
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /recaps
  static_dir: recaps
- url: /static/(.*\.appcache)
  static_files: static/\1
  mime_type: text/cache-manifest
  upload: static/(.*\.appcache)
- url: /static
  static_dir: static
- url: .*
  script: appengine_main.app

# Most of these are just the defaults, as per:
# http://code.google.com/appengine/docs/python/config/appconfig.html#Skipping_Files
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?.*\.coffee$ # Also don't send .coffee files (we compile them to .js first)
- ^(.*/)?README$ # No need to send README files.


libraries:
- name: jinja2
  version: latest
